# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='section',
            field=models.CharField(choices=[('wip', 'wip'), ('completed', 'completed'), ('future', 'future')], max_length=100),
        ),
    ]
